package api

import (
	"time"

	"github.com/meridian-lex/stratavore/pkg/types"
)

// Manually defined protobuf-compatible types
// In production, these would be generated by protoc

// ===== REQUEST TYPES =====

type LaunchRunnerRequest struct {
	ProjectName      string
	ProjectPath      string
	Flags            []string
	Capabilities     []string
	Environment      map[string]string
	ConversationMode string
	SessionID        string
	RuntimeType      string
}

type StopRunnerRequest struct {
	RunnerID       string
	Force          bool
	TimeoutSeconds int32
}

type GetRunnerRequest struct {
	RunnerID string
}

type ListRunnersRequest struct {
	ProjectName string
	Status      string
	Limit       int32
	Offset      int32
}

type CreateProjectRequest struct {
	Name        string
	Path        string
	Description string
	Tags        []string
}

type GetProjectRequest struct {
	Name string
}

type ListProjectsRequest struct {
	Status string
}

type HeartbeatRequest struct {
	RunnerID     string
	Status       string
	CPUPercent   float64
	MemoryMB     int64
	TokensUsed   int64
	SessionID    string
	AgentVersion string
	Hostname     string
}

type GetStatusRequest struct{}

type TriggerReconciliationRequest struct{}

type DeleteProjectRequest struct {
	Name string
}

type ListSessionsRequest struct {
	ProjectName string
}

type GetSessionRequest struct {
	SessionID string
}

// ===== RESPONSE TYPES =====

type LaunchRunnerResponse struct {
	Runner *Runner
	Error  string
}

type StopRunnerResponse struct {
	Success bool
	Error   string
}

type GetRunnerResponse struct {
	Runner *Runner
	Error  string
}

type ListRunnersResponse struct {
	Runners []*Runner
	Total   int32
	Error   string
}

type CreateProjectResponse struct {
	Project *Project
	Error   string
}

type GetProjectResponse struct {
	Project *Project
	Error   string
}

type ListProjectsResponse struct {
	Projects []*Project
	Error    string
}

type HeartbeatResponse struct {
	Success bool
	Command string
	Error   string
}

type GetStatusResponse struct {
	Daemon  *DaemonStatus
	Metrics *GlobalMetrics
	Error   string
}

type TriggerReconciliationResponse struct {
	ReconciledCount  int32
	FailedRunnerIDs  []string
	Error            string
}

type DeleteProjectResponse struct {
	Success bool
	Error   string
}

type ListSessionsResponse struct {
	Sessions []*types.Session
	Error    string
}

type GetSessionResponse struct {
	Session *types.Session
	Error   string
}

// ===== MODEL TYPES =====

type Runner struct {
	ID                 string
	RuntimeType        string
	RuntimeID          string
	NodeID             string
	ProjectName        string
	ProjectPath        string
	Status             string
	Flags              []string
	Capabilities       []string
	Environment        map[string]string
	SessionID          string
	ConversationMode   string
	TokensUsed         int64
	CPUPercent         float64
	MemoryMB           int64
	RestartAttempts    int32
	MaxRestartAttempts int32
	StartedAt          string
	LastHeartbeat      string
	HeartbeatTTL       int32
	TerminatedAt       string
	ExitCode           int32
	CreatedAt          string
	UpdatedAt          string
}

type Project struct {
	Name           string
	Path           string
	Status         string
	Description    string
	Tags           []string
	TotalRunners   int32
	ActiveRunners  int32
	TotalSessions  int32
	TotalTokens    int64
	CreatedAt      string
	LastAccessedAt string
	ArchivedAt     string
	UpdatedAt      string
}

type DaemonStatus struct {
	DaemonID      string
	Hostname      string
	Version       string
	StartedAt     string
	LastHeartbeat string
	Healthy       bool
}

type GlobalMetrics struct {
	ActiveRunners  int32
	ActiveProjects int32
	TotalSessions  int32
	TokensUsed     int64
	TokenLimit     int64
}

// ===== CONVERSION HELPERS =====

func FormatTime(t time.Time) string {
	if t.IsZero() {
		return ""
	}
	return t.Format(time.RFC3339)
}

func ParseTime(s string) (time.Time, error) {
	if s == "" {
		return time.Time{}, nil
	}
	return time.Parse(time.RFC3339, s)
}
