package api

import (
	"time"

	"github.com/meridian-lex/stratavore/pkg/types"
)

// Manually defined protobuf-compatible types
// In production, these would be generated by protoc

// ===== REQUEST TYPES =====

type LaunchRunnerRequest struct {
	ProjectName      string
	ProjectPath      string
	Flags            []string
	Capabilities     []string
	Environment      map[string]string
	ConversationMode string
	SessionID        string
	RuntimeType      string
}

type StopRunnerRequest struct {
	RunnerID       string
	Force          bool
	TimeoutSeconds int32
}

type GetRunnerRequest struct {
	RunnerID string
}

type ListRunnersRequest struct {
	ProjectName string
	Status      string
	Limit       int32
	Offset      int32
}

type CreateProjectRequest struct {
	Name        string
	Path        string
	Description string
	Tags        []string
}

type GetProjectRequest struct {
	Name string
}

type ListProjectsRequest struct {
	Status string
}

type HeartbeatRequest struct {
	RunnerID     string
	Status       string
	CPUPercent   float64
	MemoryMB     int64
	TokensUsed   int64
	SessionID    string
	AgentVersion string
	Hostname     string
}

type GetStatusRequest struct{}

type TriggerReconciliationRequest struct{}

type DeleteProjectRequest struct {
	Name string
}

type ListSessionsRequest struct {
	ProjectName string
}

type GetSessionRequest struct {
	SessionID string
}

// ===== RESPONSE TYPES =====

type LaunchRunnerResponse struct {
	Runner *Runner `json:"runner"`
	Error  string  `json:"error,omitempty"`
}

type StopRunnerResponse struct {
	Success bool   `json:"success"`
	Error   string `json:"error,omitempty"`
}

type GetRunnerResponse struct {
	Runner *Runner `json:"runner"`
	Error  string  `json:"error,omitempty"`
}

type ListRunnersResponse struct {
	Runners []*Runner `json:"runners"`
	Total   int32     `json:"total"`
	Error   string    `json:"error,omitempty"`
}

type CreateProjectResponse struct {
	Project *Project `json:"project"`
	Error   string   `json:"error,omitempty"`
}

type GetProjectResponse struct {
	Project *Project `json:"project"`
	Error   string   `json:"error,omitempty"`
}

type ListProjectsResponse struct {
	Projects []*Project `json:"projects"`
	Error    string     `json:"error,omitempty"`
}

type HeartbeatResponse struct {
	Success bool   `json:"success"`
	Command string `json:"command,omitempty"`
	Error   string `json:"error,omitempty"`
}

type GetStatusResponse struct {
	Daemon  *DaemonStatus  `json:"daemon"`
	Metrics *GlobalMetrics `json:"metrics"`
	Error   string         `json:"error,omitempty"`
}

type TriggerReconciliationResponse struct {
	ReconciledCount int32    `json:"reconciledCount"`
	FailedRunnerIDs []string `json:"failedRunnerIds,omitempty"`
	Error           string   `json:"error,omitempty"`
}

type DeleteProjectResponse struct {
	Success bool   `json:"success"`
	Error   string `json:"error,omitempty"`
}

type ListSessionsResponse struct {
	Sessions []*types.Session `json:"sessions"`
	Error    string           `json:"error,omitempty"`
}

type GetSessionResponse struct {
	Session *types.Session `json:"session"`
	Error   string         `json:"error,omitempty"`
}

type GetTokensRequest struct{}

type GetTokensResponse struct {
	TotalTokensUsed int64            `json:"totalTokensUsed"`
	TokensByProject map[string]int64 `json:"tokensByProject"`
	DailyLimit      int64            `json:"dailyLimit"`
	UsagePercentage float64          `json:"usagePercentage"`
	Error           string           `json:"error,omitempty"`
}

type GetModeRequest struct{}

type GetModeResponse struct {
	Mode        string `json:"mode"`
	Description string `json:"description,omitempty"`
	Error       string `json:"error,omitempty"`
}

type SetModeRequest struct {
	Mode        string `json:"mode"`
	Description string `json:"description,omitempty"`
}

type SetModeResponse struct {
	Success bool   `json:"success"`
	Mode    string `json:"mode"`
	Error   string `json:"error,omitempty"`
}

type GetConfigRequest struct{}

type GetConfigResponse struct {
	Database      DatabaseDisplayConfig      `json:"database"`
	Daemon        DaemonDisplayConfig        `json:"daemon"`
	Observability ObservabilityDisplayConfig `json:"observability"`
	Error         string                     `json:"error,omitempty"`
}

type DatabaseDisplayConfig struct {
	Host     string `json:"host"`
	Port     int    `json:"port"`
	Database string `json:"database"`
}

type DaemonDisplayConfig struct {
	HTTPPort int `json:"http_port"`
	GRPCPort int `json:"grpc_port"`
}

type ObservabilityDisplayConfig struct {
	LogLevel string `json:"log_level"`
}

type GetStateRequest struct{}

type GetStateResponse struct {
	OperationalMode string `json:"operational_mode"`
	DaemonStatus    string `json:"daemon_status"`
	Uptime          string `json:"uptime"`
	ActiveRunners   int32  `json:"active_runners"`
	TotalProjects   int32  `json:"total_projects"`
	TotalSessions   int32  `json:"total_sessions"`
	TokensUsed      int64  `json:"tokens_used"`
	Error           string `json:"error,omitempty"`
}

// ===== MODEL TYPES =====

type Runner struct {
	ID                 string            `json:"id"`
	RuntimeType        string            `json:"runtimeType"`
	RuntimeID          string            `json:"runtimeId"`
	NodeID             string            `json:"nodeId"`
	ProjectName        string            `json:"projectName"`
	ProjectPath        string            `json:"projectPath"`
	Status             string            `json:"status"`
	Flags              []string          `json:"flags"`
	Capabilities       []string          `json:"capabilities"`
	Environment        map[string]string `json:"environment"`
	SessionID          string            `json:"sessionId"`
	ConversationMode   string            `json:"conversationMode"`
	TokensUsed         int64             `json:"tokensUsed"`
	CPUPercent         float64           `json:"cpuPercent"`
	MemoryMB           int64             `json:"memoryMb"`
	RestartAttempts    int32             `json:"restartAttempts"`
	MaxRestartAttempts int32             `json:"maxRestartAttempts"`
	StartedAt          string            `json:"startedAt"`
	LastHeartbeat      string            `json:"lastHeartbeat"`
	HeartbeatTTL       int32             `json:"heartbeatTtl"`
	TerminatedAt       string            `json:"terminatedAt,omitempty"`
	ExitCode           int32             `json:"exitCode"`
	CreatedAt          string            `json:"createdAt"`
	UpdatedAt          string            `json:"updatedAt"`
}

type Project struct {
	Name           string   `json:"name"`
	Path           string   `json:"path"`
	Status         string   `json:"status"`
	Description    string   `json:"description"`
	Tags           []string `json:"tags"`
	TotalRunners   int32    `json:"totalRunners"`
	ActiveRunners  int32    `json:"activeRunners"`
	TotalSessions  int32    `json:"totalSessions"`
	TotalTokens    int64    `json:"totalTokens"`
	CreatedAt      string   `json:"createdAt"`
	LastAccessedAt string   `json:"lastAccessedAt"`
	ArchivedAt     string   `json:"archivedAt,omitempty"`
	UpdatedAt      string   `json:"updatedAt"`
}

type DaemonStatus struct {
	DaemonID      string `json:"daemonId"`
	Hostname      string `json:"hostname"`
	Version       string `json:"version"`
	StartedAt     string `json:"startedAt"`
	LastHeartbeat string `json:"lastHeartbeat"`
	Healthy       bool   `json:"healthy"`
}

type GlobalMetrics struct {
	ActiveRunners  int32 `json:"activeRunners"`
	ActiveProjects int32 `json:"activeProjects"`
	TotalSessions  int32 `json:"totalSessions"`
	TokensUsed     int64 `json:"tokensUsed"`
	TokenLimit     int64 `json:"tokenLimit"`
}

// ===== CONVERSION HELPERS =====

func FormatTime(t time.Time) string {
	if t.IsZero() {
		return ""
	}
	return t.Format(time.RFC3339)
}

func ParseTime(s string) (time.Time, error) {
	if s == "" {
		return time.Time{}, nil
	}
	return time.Parse(time.RFC3339, s)
}

// ===== Sprint API types =====

type CreateSprintRequest struct {
	Name        string   `json:"name"`
	Description string   `json:"description,omitempty"`
	ProjectName string   `json:"project_name,omitempty"`
	CreatedBy   string   `json:"created_by,omitempty"`
	Tags        []string `json:"tags,omitempty"`
}

type CreateSprintResponse struct {
	SprintID string `json:"sprint_id"`
}

type AddSprintTaskRequest struct {
	SprintID       string   `json:"sprint_id"`
	SequenceNumber int      `json:"sequence_number"`
	DependsOn      []string `json:"depends_on,omitempty"`
	Name           string   `json:"name"`
	Description    string   `json:"description,omitempty"`
	ModelName      string   `json:"model_name"`
	SystemPrompt   string   `json:"system_prompt,omitempty"`
	UserPrompt     string   `json:"user_prompt"`
	MaxTokens      int      `json:"max_tokens,omitempty"`
	Temperature    float64  `json:"temperature,omitempty"`
}

type UpdateSprintStatusRequest struct {
	SprintID string `json:"sprint_id"`
	Status   string `json:"status"`
}

type UpdateTaskResultRequest struct {
	TaskID        string                 `json:"task_id"`
	Status        string                 `json:"status"`
	ResultSummary string                 `json:"result_summary,omitempty"`
	ResultData    map[string]interface{} `json:"result_data,omitempty"`
	TokensInput   int64                  `json:"tokens_input,omitempty"`
	TokensOutput  int64                  `json:"tokens_output,omitempty"`
	CostUSD       float64                `json:"cost_usd,omitempty"`
	ErrorMessage  string                 `json:"error_message,omitempty"`
}

type UpdateModelRequest struct {
	Enabled *bool                  `json:"enabled,omitempty"`
	Config  map[string]interface{} `json:"config,omitempty"`
}
